### ISSUE TITLE
Make Output creation more obvious

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#112]
**Describe the bug**
Hi, since I was used to the old behavior of adding outputs, it took some time to figure out how to do it now.
I had to create a Board object which is not intuitive in my opinion.
It could be good to state this inside "Output" table widget and "Output" tab inside Interface details widget which both are now read-only.
There could be a tooltip or small text saying "Go to Boards and add the turnout there..."

Other small issues:

1. Creating 2 turnouts and setting them to a Z21 it always starts from address 1. Is this intended behavior?
2. In the turnout page, Output Tab: third column header just shows `#1`, add a tooltip "Address 1"
3. Could we assign by default "First/Second" for newly created Outputs? Or at least warn the user if every action is set to "None"
4. I cannot disable some of the position of a double slip switch
5. "Enabled" could be better than "Use" for `output_map:use`.
6. Some position of double slip switch are not translated in Italian, I need to check better the English file as well.
7. If I double click on an output inside the "Outputs" table, it show a window with "Invalid Object" error message on it. Same if output is clicked from Interface tabwidget.

**Comment by gfgit** [comment]
Ok now I understood point 2.
`#1` is the address of associated Output. It could be made more clear, like "Address 1" or with a tooltip.
This new way of adding outputs is very cool by the way, especially when you need more addresses for a turnout like a double slip switch

**Comment by gfgit** [comment]
> 4\. I cannot disable some of the position of a double slip switch

See `outputmapitembase.hpp#60`

**Comment by reinder** [comment]
Yeah it is a bit different since you last used it, I refactored the output system to support different types of outputs, I wanted to add support for DCCext and wasn't happy with the create output and then add it to the turnout process.
Most users will also expect to set a "turnout address" in the turnout dialog as that is what other automation software does too. See #21 and #95. I think this is only an issue for users that were used to the old situation. For decoders and input I'd planned to do a similar refactor, but that will be for the 0.4 version.

> 1. Creating 2 turnouts and setting them to a Z21 it always starts from address 1. Is this intended behavior?

Uhm, that is up to discussion :) I think selecting a "free" address is better. In some cases you might want to use duplicate addresses, but usually each turnout/signal has a unique one. What do you think is best?

> 2. In the turnout page, Output Tab: third column header just shows #1, possibly Italian translation missing...
>
> Ok now I understood point 2.
> #1 is the address of associated Output. It could be made more clear, like "Address 1" or with a tooltip.
> This new way of adding outputs is very cool by the way, especially when you need more addresses for a turnout like a double slip switch

To save some space I choose to use #address, adding a tooltip is a good suggestion, I'll add one.

> 3. Could we assign by default "First/Second" for newly created Outputs? Or at least warn the user if every action is set to "None"

Yes, that is missing now (also for DCCext), when there is only one output a "swap" button is also useful in case it is wired differently.

> 4. I cannot disable some of the position of a double slip switch
> 5. "Enabled" could be better than "Use" for output_map:use.

Maybe we should just add an option if it is single or dual motor and then only list those positions. I think that are the two variants and then it is less error prone for the user. 

> 6. Some position of double slip switch are not translated in Italian, I need to check better the English file as well.

If you enable Traintastic Client -> Settings -> Developer -> Don't load fallback language, it won't load the English string and just show the ID, that makes it easier to find it.

**Comment by reinder** [comment]
> This new way of adding outputs is very cool by the way, especially when you need more addresses for a turnout like a double slip switch

Thanks :)

**Comment by gfgit** [comment]
Added point 7

**Comment by gfgit** [comment]
> Maybe we should just add an option if it is single or dual motor and then only list those positions. I think that are the two variants and then it is less error prone for the user.

I like the current approach which is more "advanced" and which could cover some very specific situations if needed.
Double slip switches are all dual motor for what I know. Crossing and Diverged positions I think need a third motor but I'm not sure about this.
Anyway checkbox was calling me to click on it :)

**Comment by reinder** [comment]
The *Fleischmann 6066* I have are single motor, they only have a crossed and diverged position.

When reserving a path it only "uses" the specific ones as crossed and diverged are super sets then. But these slip switches will require some more work I think. Most import (my opinion) is that it must be easy to setup for users.

> 7. If I double click on an output inside the "Outputs" table, it show a window with "Invalid Object" error message on it. Same if output is clicked from Interface tabwidget.

Good catch, going to fix that.

**Comment by reinder** [comment]
> 1. Creating 2 turnouts and setting them to a Z21 it always starts from address 1. Is this intended behavior?

Fixed it, it was already working in the server...but the client broke it due to incorrect min/max values from the server.

**Comment by reinder** [comment]
> 4. I cannot disable some of the position of a double slip switch
> 5. "Enabled" could be better than "Use" for output_map:use.

These are the only remaining (the rest is fixed), going to think about it a bit, I'm still not happy with all the options being lists for slip switches.

**Comment by reinder** [comment]
@gfgit I've added a "Dual motor/coil" setting that controls the available positions for slip turnouts. Going to improve the output mapping further by removing the "use" column for all output maps except signals and add images to the table :)

**Comment by reinder** [comment]
@gfgit I've added icons too, I'd hope this new output mapping is better than the old version :)

**Comment by gfgit** [comment]
Closing old issue. Recent commits have fixed this.
