### ISSUE TITLE
Log Invalid parameter passed to C runtime

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#35]
**Describe the bug**
Hi, I'm getting a lot of "Invalid parameter passed to C runtime" running server built with MinGW 12.2.0.

I suspect the warning message is sent after calling `std::put_time()` and it's `operator<<` from [CosoleLogger](https://github.com/traintastic/traintastic/blob/7397cb9e16652d880abf63079155a7a4b34f179b/server/src/log/consolelogger.cpp#L48)

The message is sent early and sometimes gets printed before other calls to `std::cout` or `printf()` so I first thought it was `localtime_s()` fault but now I know it's not that.

The variables seem fine and also passed format argument `%F %T` but it doesn't print anything

**Comment by gfgit** [comment]
[CppReference](https://en.cppreference.com/w/cpp/io/manip/put_time) says that "T" and "F" are available only C++11.
"%H:%M:%S" works so maybe the C runtime is not C++11?

**Comment by reinder** [comment]
C++11 means since C++11 on CppReference.

It seems to be a MinGW bug, see https://sourceforge.net/p/mingw-w64/bugs/793/

Think it is best to add a #define with the log format, then we can define it differently for MinGW and add a comment about the MinGW bug. The [FileLogger](https://github.com/traintastic/traintastic/blob/7397cb9e16652d880abf63079155a7a4b34f179b/server/src/log/filelogger.cpp#L59) also uses them using a semicolon instead of a space as separator.
