### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#8]
**Describe the bug**
This world is special because it doesn't like you creating a new one.
Server crashes in assert failure at [inputlist.cpp](https://github.com/traintastic/traintastic/blob/722b9650fa3915bbe4ddce2a63d74efe5d11dfcb/server/src/hardware/input/list/inputlist.cpp#L47)

I hope backtrace is useful: [backtrace.txt](https://github.com/traintastic/traintastic/files/10429881/backtrace.txt)
Current `const std::shared_ptr<Input>& input` is `input_1` object and is the only one contained in the list.

**To Reproduce**
1. Open world linked below
2. Click on File -> New world
3. Connection lost because crash

**Expected behavior**
No crash

**World export**
Zip of uncompressed folder.
[9f0bff1f-6aa8-4c66-9fd9-65090f4e579a.zip](https://github.com/traintastic/traintastic/files/10429870/9f0bff1f-6aa8-4c66-9fd9-65090f4e579a.zip)

**Traintastic server:**
 - OS: Windows 10, MinGW 11.20
 - Version: [e.g. 0.1.1]

**Traintastic client:**
 - Same as server

**Connected hardware**
None

**Comment by gfgit** [comment]
Additional crash, this time with Decoders: [decoderlist.cpp](https://github.com/traintastic/traintastic/blob/722b9650fa3915bbe4ddce2a63d74efe5d11dfcb/server/src/hardware/decoder/list/decoderlist.cpp#L51)

1. Load world: 
[9f0bff1f-6aa8-4c66-9fd9-65090f4e579a.zip](https://github.com/traintastic/traintastic/files/10429938/9f0bff1f-6aa8-4c66-9fd9-65090f4e579a.zip)
NOTE: UUID is the same as the first post but files are different
2. File -> Close world
3. Server Crash

**Comment by reinder** [comment]
I had this one also last weekend, already looking into it. Thank you for reporting.

**Comment by reinder** [comment]
Investigated the issue:
- Crash was caused by closing/destroying the world. (this is done also when a new world is created.)
- Only occurred in Debug mode, in Release asserts are disabled.

```cpp
[IFNDEF_NDEBUG(this)](const std::shared_ptr<Decoder>& decoder) // <-- not the reference here
{
  if(!decoder)
    return;
  decoder->destroy(); // <-- this destroy's the object by letting other object drop there shared_ptr's to it.
  assert(!containsObject(decoder));
}}
```

So why does the `assert` fail? The key is the reference argument. In case of a world destroy this reference is a reference to a `shared_ptr` in the _this_ list. The `destroy()` call indeed removes the item from the list BUT, there is another `shared_ptr` in that list that is now on the memory address of the removed `shared_ptr`, so `decoder` now points to another `shared_ptr`, which is still in the list causing the `assert` to fail.
