### ISSUE TITLE
Server crashes after start

### ISSUE THREAD

**Issue by gmazzucchi** [traintastic/traintastic#89]
**Describe the bug**
When running the server, it crashes immediately with this message:
traintastic-server: ~/thirdparty/traintastic/server/src/log/logger.cpp:37: static std::string_view Logger::toString(LogMessage): Assertion `Locale::tr(key) != key' failed.
[1]    95493 IOT instruction (core dumped)  ./traintastic-server

**To Reproduce**
Just build and running the server.

**Expected behavior**
Starting and logging that it has no connected hardware.

**Traintastic server:**
 - OS: Ubuntu 22.04
 - Version: just cloned the master

**Connected hardware**
- Just starting the server without connected hardware.

**Comment by gfgit** [comment]
Hi, this happens because some log messages not translated yet.
@reinder we should add a debug message with contents of `key` to ease debugging.

**Comment by reinder** [comment]
Hi @gmazzucchi ,

It stopped on an `assert()` most likely because it can't load the translation files. By default Traintastic loads them from the folder where Traintastic is installed normally. For development builds this doesn't work when Traintastic isn't installed. Therefor the environment variable can be set to override that. e.g. set `TRAINTASTIC_LOCALE_PATH` to `/home/reinder/traintastic/shared/translations`.

@gfgit This is indeed something that should be improved a bit, I'll look into it.

**Comment by gmazzucchi** [comment]
Yes, it works. Thank you for the support.

**Comment by reinder** [comment]
Great! I'm adding an addition check to the software so it will give a proper error on startup if it can't load the language file.
Then I'll close the issue :)

If you have further questions or suggestions, feel free to open an issue or start a discussion.
