### ISSUE TITLE
Cannot reliably trigger Simulation mode

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#9]
**Describe the bug**
Needs more investigation.
When opening saved world with multiple interfaces (one for each type available), the are all offline.
I try to enable Simulation (tricky because connection must be off first and powered off).
Some interfaces have the Online checkbox disabled (grayed out) so I cannot click on it to enable them.
This happens in particular with Traintastic DIY.
If Traintastic DIY is alone, it works.

**Comment by gfgit** [comment]
Putting a breaking point in `Interface::worldEvent()`, when having many interfaces it doesn't get called for Traintastic DIY object so online status is not propagated I suppose

**Comment by reinder** [comment]
Thanks for reporting, I will look into it.

**Comment by reinder** [comment]
Some background:
*Simulation* may only be toggled when the world is *offline* because the world is in simulation mode or not.
*Interface online* can only be toggled when the world is *online*, when the world is offline all interfaces are forced offline.

The bug:
If an interface can't go online for some reason the interfaces *online* property doesn't accept the `true` and raises an exception. This exception is the issue, this causes the "put all interfaces online" process to stop.
